apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-delete-hook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: pre-delete-hook
          image: alpine:3.19
          command: ["sh", "-c", "echo 'Running pre-delete hook'; sleep 10; kubectl delete ns eli-test; echo 'Hook completed'"]
      restartPolicy: Never
